#开发环境
spring:
  #配置数据源
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///blog?serverTimezone=GMT&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
#配置日志
logging:
  level:
    root: info
    com.fly: debug
  file: log/blog-dev.log

server:
  port: 8081
